# Generated By AI Start (Cursor)
"""Synthetic WESAD-like fixtures for unit tests."""

from __future__ import annotations

import pickle
from pathlib import Path

import numpy as np
import pytest


def make_synthetic_subject(subject_id: str = "S99", duration_s: float = 180.0) -> dict:
    fs = 700
    n = int(duration_s * fs)
    t = np.arange(n) / fs

    baseline = (t < 60)
    stress = (t >= 60) & (t < 120)
    amusement = (t >= 120)

    labels = np.zeros(n, dtype=int)
    labels[baseline] = 1
    labels[stress] = 2
    labels[amusement] = 3

    chest_ecg = 0.5 * np.sin(2 * np.pi * 1.2 * t) + 0.05 * np.random.randn(n)
    chest_eda = 2.0 + 0.2 * stress.astype(float) + 0.02 * np.random.randn(n)
    chest_emg = 0.05 * np.random.randn(n)
    chest_temp = 33.0 + 0.01 * t + 0.005 * np.random.randn(n)
    chest_resp = np.sin(2 * np.pi * 0.25 * t) + 0.05 * np.random.randn(n)
    chest_acc = np.column_stack([0.1 * np.random.randn(n) for _ in range(3)])

    wrist_n_eda = int(duration_s * 4)
    wrist_t = np.arange(wrist_n_eda) / 4
    wrist_eda = 2.0 + 0.15 * (wrist_t >= 60) * (wrist_t < 120) + 0.02 * np.random.randn(wrist_n_eda)
    wrist_bvp = np.sin(2 * np.pi * 1.1 * wrist_t) + 0.05 * np.random.randn(wrist_n_eda)
    wrist_temp = 32.5 + 0.005 * wrist_t + 0.005 * np.random.randn(wrist_n_eda)
    wrist_n_acc = int(duration_s * 32)
    wrist_acc = np.column_stack([0.2 * np.random.randn(wrist_n_acc) for _ in range(3)])

    return {
        "signal": {
            "chest": {
                "ACC": chest_acc,
                "ECG": chest_ecg.reshape(-1, 1),
                "EMG": chest_emg.reshape(-1, 1),
                "EDA": chest_eda.reshape(-1, 1),
                "Temp": chest_temp.reshape(-1, 1),
                "Resp": chest_resp.reshape(-1, 1),
            },
            "wrist": {
                "ACC": wrist_acc,
                "BVP": wrist_bvp.reshape(-1, 1),
                "EDA": wrist_eda.reshape(-1, 1),
                "TEMP": wrist_temp.reshape(-1, 1),
            },
        },
        "label": labels,
        "subject": subject_id.replace("S", ""),
    }


def write_synthetic_subject(out_dir: Path, subject_id: str = "S99") -> Path:
    out_dir.mkdir(parents=True, exist_ok=True)
    subject_dir = out_dir / subject_id
    subject_dir.mkdir(parents=True, exist_ok=True)
    payload = make_synthetic_subject(subject_id)
    pkl_path = subject_dir / f"{subject_id}.pkl"
    with pkl_path.open("wb") as handle:
        pickle.dump(payload, handle)
    return pkl_path


@pytest.fixture
def synthetic_cfg() -> dict:
    return {
        "sampling_rates": {"label": 700, "chest": 700, "wrist": {"ACC": 32, "BVP": 64, "EDA": 4, "TEMP": 4}},
        "windowing": {"window_seconds": 60, "step_seconds": 30, "label_majority_threshold": 0.8},
        "labels": {"baseline": 1, "stress": 2, "amusement": 3, "exclude": [0, 4, 5, 6, 7]},
    }
# Generated By AI End (Cursor)
