# Generated By AI Start (Cursor)
"""Tests for EDA feature extraction."""

import numpy as np

from wesad_arousal.features.eda import extract_eda_features


def test_eda_features_on_synthetic_signal():
    fs = 4
    signal = 2.0 + 0.1 * np.sin(2 * np.pi * 0.05 * np.arange(0, 60, 1 / fs))
    feats = extract_eda_features(signal, fs, prefix="eda")
    assert feats["eda_mean"] > 0
    assert 0.0 <= feats["eda_valid_range_pct"] <= 1.0
# Generated By AI End (Cursor)
