# Generated By AI Start (Cursor)
"""Tests for QC metrics and preprocessing integration."""

from pathlib import Path

import numpy as np

from wesad_arousal.config import load_config
from wesad_arousal.data import preprocess_all_subjects
from wesad_arousal.quality import compute_signal_qc
from conftest import write_synthetic_subject


def test_compute_signal_qc_flatline():
    signal = np.ones(1000)
    metrics = compute_signal_qc(signal, "EDA", "wrist", fs=4.0, valid_range=(0.0, 10.0))
    assert metrics["flatline_fraction"] > 0.9
    assert metrics["missingness"] == 0.0


def test_preprocess_synthetic_subject(tmp_path):
    raw_dir = tmp_path / "raw"
    write_synthetic_subject(raw_dir, "S99")
    cfg = load_config(Path("configs/default.yaml"))
    cfg["paths"]["raw_dir"] = str(raw_dir)
    cfg["paths"]["interim_dir"] = str(tmp_path / "interim")
    cfg["subjects"]["ids"] = [99]

    processed = preprocess_all_subjects(cfg)
    assert processed == ["S99"]
    assert (tmp_path / "interim" / "S99" / "labels.npy").exists()
# Generated By AI End (Cursor)
