# Generated By AI Start (Cursor)
"""Tests for sliding-window generation."""

import numpy as np

from wesad_arousal.features.windowing import generate_windows, windows_to_dataframe


def test_generate_windows_majority_vote(synthetic_cfg):
    fs = synthetic_cfg["sampling_rates"]["label"]
    n = int(180 * fs)
    labels = np.full(n, -1, dtype=int)
    labels[: int(70 * fs)] = 1
    labels[int(70 * fs) : int(130 * fs)] = 2
    labels[int(130 * fs) :] = 3

    windows = generate_windows(
        labels=labels,
        fs=fs,
        window_seconds=60,
        step_seconds=30,
        cfg=synthetic_cfg,
        majority_threshold=0.8,
    )
    assert len(windows) > 0
    names = {w.label_name for w in windows}
    assert "baseline" in names
    assert "stress" in names

    df = windows_to_dataframe(windows, "S99")
    assert "label_purity" in df.columns
    assert df["label_purity"].min() >= 0.8
# Generated By AI End (Cursor)
