# Generated By AI Start (Cursor)
"""Tests for HRV feature extraction."""

import numpy as np

from wesad_arousal.features.hrv import extract_hrv_features


def test_hrv_features_on_synthetic_ecg():
    fs = 700
    t = np.arange(0, 30, 1 / fs)
    ecg = np.sin(2 * np.pi * 1.2 * t)
    feats = extract_hrv_features(ecg, fs, prefix="hrv")
    assert "hrv_hr_mean" in feats
    assert "hrv_peak_success_rate" in feats
    assert feats["hrv_hr_mean"] >= 0
# Generated By AI End (Cursor)
