# Generated By AI Start (Cursor)
"""Configuration loading and path resolution."""

from __future__ import annotations

from pathlib import Path
from typing import Any

import yaml


def _deep_merge(base: dict[str, Any], override: dict[str, Any]) -> dict[str, Any]:
    merged = dict(base)
    for key, value in override.items():
        if key == "defaults":
            continue
        if isinstance(value, dict) and isinstance(merged.get(key), dict):
            merged[key] = _deep_merge(merged[key], value)
        else:
            merged[key] = value
    return merged


def load_config(config_path: str | Path) -> dict[str, Any]:
    path = Path(config_path)
    if not path.exists():
        raise FileNotFoundError(f"Config not found: {path}")

    with path.open("r", encoding="utf-8") as handle:
        cfg = yaml.safe_load(handle) or {}

    defaults_name = cfg.get("defaults")
    if defaults_name:
        defaults_path = path.parent / defaults_name
        if defaults_path.exists():
            with defaults_path.open("r", encoding="utf-8") as handle:
                base = yaml.safe_load(handle) or {}
            cfg = _deep_merge(base, cfg)

    root = path.parent.parent.resolve()
    paths = cfg.setdefault("paths", {})
    for key in ("raw_dir", "interim_dir", "processed_dir", "outputs_dir", "reports_dir"):
        if key in paths and not Path(paths[key]).is_absolute():
            paths[key] = str((root / paths[key]).resolve())

    return cfg


def ensure_dirs(cfg: dict[str, Any]) -> None:
    for key in ("interim_dir", "processed_dir", "outputs_dir", "reports_dir"):
        Path(cfg["paths"][key]).mkdir(parents=True, exist_ok=True)
    figures = Path(cfg["paths"]["reports_dir"]) / "figures"
    tables = Path(cfg["paths"]["reports_dir"]) / "tables"
    figures.mkdir(parents=True, exist_ok=True)
    tables.mkdir(parents=True, exist_ok=True)
# Generated By AI End (Cursor)
