# Generated By AI Start (Cursor)
"""Conservative preprocessing helpers."""

from __future__ import annotations

import numpy as np
from scipy import signal as scipy_signal


def bandpass_filter(
    data: np.ndarray,
    fs: float,
    low: float,
    high: float,
    order: int = 3,
) -> np.ndarray:
    arr = np.asarray(data, dtype=float)
    if arr.size < order * 3:
        return arr
    nyq = 0.5 * fs
    low_norm = max(low / nyq, 1e-4)
    high_norm = min(high / nyq, 0.99)
    if low_norm >= high_norm:
        return arr
    b, a = scipy_signal.butter(order, [low_norm, high_norm], btype="band")
    return scipy_signal.filtfilt(b, a, arr)


def lowpass_filter(data: np.ndarray, fs: float, cutoff: float, order: int = 3) -> np.ndarray:
    arr = np.asarray(data, dtype=float)
    if arr.size < order * 3:
        return arr
    nyq = 0.5 * fs
    norm = min(cutoff / nyq, 0.99)
    b, a = scipy_signal.butter(order, norm, btype="low")
    return scipy_signal.filtfilt(b, a, arr)


def zscore(data: np.ndarray) -> np.ndarray:
    arr = np.asarray(data, dtype=float)
    std = np.std(arr)
    if std <= 0:
        return arr - np.mean(arr)
    return (arr - np.mean(arr)) / std


def safe_stat(data: np.ndarray, fn, default: float = 0.0) -> float:
    arr = np.asarray(data, dtype=float)
    arr = arr[np.isfinite(arr)]
    if arr.size == 0:
        return default
    return float(fn(arr))
# Generated By AI End (Cursor)
