# Generated By AI Start (Cursor)
"""Figure generation for reports and README."""

from __future__ import annotations

from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import seaborn as sns


def _save(fig, path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    fig.tight_layout()
    fig.savefig(path, dpi=150, bbox_inches="tight")
    plt.close(fig)


def plot_pipeline_diagram(out_path: Path) -> None:
    fig, ax = plt.subplots(figsize=(10, 3))
    ax.axis("off")
    stages = [
        "WESAD .pkl",
        "Preprocess",
        "QC",
        "Windowing",
        "Features",
        "LOSO Models",
        "Reports",
    ]
    xs = np.linspace(0.05, 0.95, len(stages))
    for x, stage in zip(xs, stages):
        ax.text(x, 0.5, stage, ha="center", va="center", bbox=dict(boxstyle="round", fc="#E8F1FF"))
    for i in range(len(xs) - 1):
        ax.annotate("", xy=(xs[i + 1] - 0.05, 0.5), xytext=(xs[i] + 0.05, 0.5), arrowprops=dict(arrowstyle="->"))
    ax.set_title("WESAD Arousal Phenotyping Pipeline")
    _save(fig, out_path)


def plot_qc_heatmap(qc_df: pd.DataFrame, out_path: Path) -> None:
    numeric = qc_df.select_dtypes(include=[np.number])
    if numeric.empty:
        return
    pivot = qc_df.pivot_table(
        index="subject_id",
        columns="signal",
        values="missingness",
        aggfunc="mean",
    )
    fig, ax = plt.subplots(figsize=(8, 5))
    sns.heatmap(pivot, cmap="YlOrRd", ax=ax)
    ax.set_title("Signal Missingness by Subject and Modality")
    _save(fig, out_path)


def plot_feature_distributions(features_df: pd.DataFrame, out_path: Path) -> None:
    candidates = [col for col in features_df.columns if col.startswith(("chest_eda", "chest_hrv", "wrist_eda"))]
    if not candidates:
        return
    col = candidates[0]
    fig, ax = plt.subplots(figsize=(7, 4))
    sns.boxplot(data=features_df, x="label_name", y=col, ax=ax)
    ax.set_title(f"Feature Distribution by Condition: {col}")
    _save(fig, out_path)


def plot_confusion_matrix(cm: list[list[int]], labels: list[str], out_path: Path) -> None:
    fig, ax = plt.subplots(figsize=(5, 4))
    sns.heatmap(np.asarray(cm), annot=True, fmt="d", cmap="Blues", xticklabels=labels, yticklabels=labels, ax=ax)
    ax.set_xlabel("Predicted")
    ax.set_ylabel("True")
    ax.set_title("LOSO Confusion Matrix")
    _save(fig, out_path)


def plot_ablation(ablation_df: pd.DataFrame, out_path: Path) -> None:
    fig, ax = plt.subplots(figsize=(7, 4))
    sns.barplot(data=ablation_df, x="ablation", y="balanced_accuracy", ax=ax, color="#4C78A8")
    ax.tick_params(axis="x", rotation=30)
    ax.set_title("Modality Ablation (Random Forest, LOSO)")
    _save(fig, out_path)


def plot_feature_importance(importance_df: pd.DataFrame, out_path: Path, top_n: int = 15) -> None:
    top = importance_df.head(top_n)
    fig, ax = plt.subplots(figsize=(7, 5))
    sns.barplot(data=top, y="feature", x="importance", ax=ax, color="#72B7B2")
    ax.set_title("Top Feature Importances")
    _save(fig, out_path)
# Generated By AI End (Cursor)
