# Generated By AI Start (Cursor)
"""CLI: generate QC and analysis reports."""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

from wesad_arousal.config import ensure_dirs, load_config
from wesad_arousal.reporting import generate_full_report, render_qc_report


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Generate markdown reports and figures")
    parser.add_argument("--config", default="configs/default.yaml")
    parser.add_argument("--qc", default=None, help="Optional QC CSV path")
    parser.add_argument("--out", default=None, help="Optional QC markdown output path")
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    cfg = load_config(ROOT / args.config)
    ensure_dirs(cfg)

    if args.qc and args.out:
        render_qc_report(Path(args.qc), Path(args.out))
        print(f"Wrote QC report to {args.out}")
        return

    report_path = generate_full_report(cfg)
    print(f"Generated report assets under {cfg['paths']['reports_dir']} (QC: {report_path})")


if __name__ == "__main__":
    main()
# Generated By AI End (Cursor)
