# Generated By AI Start (Cursor)
"""CLI: evaluate chest, wrist, and ablation configurations."""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

import pandas as pd

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

from wesad_arousal.config import ensure_dirs, load_config
from wesad_arousal.modeling.evaluation import run_loso_evaluation, save_evaluation_outputs


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Run sensor and modality comparison evaluations")
    parser.add_argument("--config", default="configs/default.yaml")
    return parser.parse_args()


def _prefixes_for_cfg(cfg: dict) -> list[str]:
    prefixes = []
    if cfg["devices"]["use_chest"]:
        prefixes.extend(["chest_"])
    if cfg["devices"]["use_wrist"]:
        prefixes.extend(["wrist_"])
    return prefixes


def main() -> None:
    args = parse_args()
    cfg = load_config(ROOT / args.config)
    ensure_dirs(cfg)

    features_path = Path(cfg["paths"]["processed_dir"]) / "features.parquet"
    features_df = pd.read_parquet(features_path)

    comparisons = [
        ("chest", ROOT / "configs/sensors_chest.yaml"),
        ("wrist", ROOT / "configs/sensors_wrist.yaml"),
        ("both", ROOT / "configs/default.yaml"),
    ]

    for tag, config_path in comparisons:
        sub_cfg = load_config(config_path)
        prefixes = _prefixes_for_cfg(sub_cfg)
        meta = [c for c in features_df.columns if c in {
            "subject_id", "window_start_s", "window_end_s", "label_code",
            "label_name", "binary_label", "label_purity",
        }]
        feature_cols = [c for c in features_df.columns if any(c.startswith(p) for p in prefixes) or c in meta]
        subset = features_df[feature_cols]
        results = run_loso_evaluation(subset, sub_cfg)
        save_evaluation_outputs(results, cfg, tag=tag)
        print(f"Evaluated {tag} configuration")


if __name__ == "__main__":
    main()
# Generated By AI End (Cursor)
