# Generated By AI Start (Cursor)
"""CLI: preprocess WESAD subjects into interim parquet files."""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

from wesad_arousal.config import ensure_dirs, load_config
from wesad_arousal.data import preprocess_all_subjects


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Preprocess WESAD subject .pkl files")
    parser.add_argument("--config", default="configs/default.yaml", help="Path to YAML config")
    parser.add_argument("--raw-dir", default=None, help="Override raw WESAD directory")
    parser.add_argument("--out-dir", default=None, help="Override interim output directory")
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    cfg = load_config(ROOT / args.config)
    ensure_dirs(cfg)
    subjects = preprocess_all_subjects(cfg, raw_dir=args.raw_dir, out_dir=args.out_dir)
    print(f"Preprocessed {len(subjects)} subjects into {cfg['paths']['interim_dir']}")


if __name__ == "__main__":
    main()
# Generated By AI End (Cursor)
