# Generated By AI Start (Cursor)
"""CLI: train baseline models with leave-one-subject-out CV."""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

import pandas as pd

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

from wesad_arousal.config import ensure_dirs, load_config
from wesad_arousal.modeling.evaluation import run_loso_evaluation, save_evaluation_outputs


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Train and evaluate baseline models (LOSO)")
    parser.add_argument("--config", default="configs/default.yaml")
    parser.add_argument("--task", choices=["binary", "multiclass"], default=None)
    parser.add_argument("--tag", default="default", help="Output tag for metrics files")
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    cfg = load_config(ROOT / args.config)
    ensure_dirs(cfg)

    features_path = Path(cfg["paths"]["processed_dir"]) / "features.parquet"
    if not features_path.exists():
        raise FileNotFoundError(f"Feature file not found: {features_path}. Run run_extract_features.py first.")

    features_df = pd.read_parquet(features_path)
    task = args.task or cfg.get("modeling", {}).get("task", "binary")
    results = run_loso_evaluation(features_df, cfg, task=task)
    out = save_evaluation_outputs(results, cfg, tag=args.tag)
    print(f"Saved evaluation metrics to {out}")


if __name__ == "__main__":
    main()
# Generated By AI End (Cursor)
