# Generated By AI Start (Cursor)
"""Baseline classifiers for stress and arousal phenotyping."""

from __future__ import annotations

from sklearn.dummy import DummyClassifier
from sklearn.ensemble import HistGradientBoostingClassifier, RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler


def get_model(name: str, random_state: int = 42) -> Pipeline:
    models = {
        "dummy": DummyClassifier(strategy="stratified", random_state=random_state),
        "logistic": LogisticRegression(max_iter=2000, random_state=random_state),
        "random_forest": RandomForestClassifier(
            n_estimators=200,
            random_state=random_state,
            class_weight="balanced_subsample",
            n_jobs=-1,
        ),
        "gradient_boosting": HistGradientBoostingClassifier(random_state=random_state),
    }
    if name not in models:
        raise ValueError(f"Unknown model: {name}. Available: {list(models)}")

    estimator = models[name]
    if name == "dummy":
        return Pipeline([("model", estimator)])
    return Pipeline([("scaler", StandardScaler()), ("model", estimator)])


def list_models(cfg: dict) -> list[str]:
    return list(cfg.get("modeling", {}).get("models", ["dummy", "logistic", "random_forest", "gradient_boosting"]))
# Generated By AI End (Cursor)
