# Generated By AI Start (Cursor)
"""Electrodermal activity features."""

from __future__ import annotations

import numpy as np

from wesad_arousal.preprocessing import lowpass_filter, safe_stat


def extract_eda_features(eda: np.ndarray, fs: float, prefix: str = "eda") -> dict[str, float]:
    signal = np.asarray(eda, dtype=float).reshape(-1)
    if signal.size == 0:
        return _empty_eda(prefix)

    smoothed = lowpass_filter(signal, fs, cutoff=1.0)
    valid_range = (0.01, 60.0)
    in_range = np.mean((smoothed >= valid_range[0]) & (smoothed <= valid_range[1]))

    try:
        import neurokit2 as nk

        processed = nk.eda_process(smoothed, sampling_rate=fs)
        tonic = processed["EDA_Tonic"].to_numpy(dtype=float)
        phasic = processed["EDA_Phasic"].to_numpy(dtype=float)
        scr_count = float(np.sum(phasic > 0.01))
        scr_amp = safe_stat(phasic[phasic > 0.01], np.mean) if np.any(phasic > 0.01) else 0.0
    except Exception:
        tonic = smoothed
        phasic = smoothed - np.mean(smoothed)
        scr_count = float(np.sum(phasic > 0.05 * np.std(phasic))) if np.std(phasic) > 0 else 0.0
        scr_amp = safe_stat(phasic, lambda x: np.mean(np.abs(x)))

    return {
        f"{prefix}_mean": safe_stat(smoothed, np.mean),
        f"{prefix}_std": safe_stat(smoothed, np.std),
        f"{prefix}_tonic_mean": safe_stat(tonic, np.mean),
        f"{prefix}_phasic_mean": safe_stat(phasic, np.mean),
        f"{prefix}_phasic_std": safe_stat(phasic, np.std),
        f"{prefix}_scr_count": scr_count,
        f"{prefix}_scr_amplitude": scr_amp,
        f"{prefix}_valid_range_pct": float(in_range),
    }


def _empty_eda(prefix: str) -> dict[str, float]:
    keys = [
        "mean",
        "std",
        "tonic_mean",
        "phasic_mean",
        "phasic_std",
        "scr_count",
        "scr_amplitude",
        "valid_range_pct",
    ]
    return {f"{prefix}_{key}": 0.0 for key in keys}
# Generated By AI End (Cursor)
