# Generated By AI Start (Cursor)
"""ECG and heart rate variability features."""

from __future__ import annotations

import numpy as np

from wesad_arousal.preprocessing import bandpass_filter, safe_stat


def _fallback_hrv_features(signal: np.ndarray, fs: float, prefix: str) -> dict[str, float]:
    diff = np.diff(signal) if signal.size > 1 else np.array([0.0])
    peak_proxy = safe_stat(np.abs(diff), np.mean)
    return {
        f"{prefix}_hr_mean": peak_proxy * fs * 60.0 / 100.0,
        f"{prefix}_hr_std": safe_stat(diff, np.std),
        f"{prefix}_rmssd": safe_stat(diff, lambda x: np.sqrt(np.mean(x ** 2))),
        f"{prefix}_sdnn": safe_stat(signal, np.std),
        f"{prefix}_pnn50": 0.0,
        f"{prefix}_peak_success_rate": 0.0,
    }


def extract_hrv_features(ecg: np.ndarray, fs: float, prefix: str = "hrv") -> dict[str, float]:
    signal = np.asarray(ecg, dtype=float).reshape(-1)
    if signal.size < fs * 5:
        features = _fallback_hrv_features(signal, fs, prefix)
        features[f"{prefix}_peak_success_rate"] = 0.0
        return features

    filtered = bandpass_filter(signal, fs, low=0.5, high=40.0)

    try:
        import neurokit2 as nk

        cleaned = nk.ecg_clean(filtered, sampling_rate=fs)
        _, rpeaks = nk.ecg_peaks(cleaned, sampling_rate=fs)
        peaks = rpeaks.get("ECG_R_Peaks", [])
        peaks = np.asarray(peaks, dtype=int)
        peaks = peaks[peaks > 0]

        if peaks.size < 3:
            features = _fallback_hrv_features(filtered, fs, prefix)
            features[f"{prefix}_peak_success_rate"] = _peak_success_rate(peaks.size, signal.size, fs)
            return features

        rr = np.diff(peaks) / fs
        rr = rr[(rr > 0.3) & (rr < 2.0)]
        if rr.size < 2:
            features = _fallback_hrv_features(filtered, fs, prefix)
            features[f"{prefix}_peak_success_rate"] = _peak_success_rate(peaks.size, signal.size, fs)
            return features

        hr = 60.0 / rr
        diff_rr = np.diff(rr)
        pnn50 = float(np.mean(np.abs(diff_rr) > 0.05) * 100.0) if diff_rr.size else 0.0

        features = {
            f"{prefix}_hr_mean": safe_stat(hr, np.mean),
            f"{prefix}_hr_std": safe_stat(hr, np.std),
            f"{prefix}_rmssd": safe_stat(diff_rr, lambda x: np.sqrt(np.mean(x ** 2))),
            f"{prefix}_sdnn": safe_stat(rr, np.std),
            f"{prefix}_pnn50": pnn50,
            f"{prefix}_peak_success_rate": _peak_success_rate(peaks.size, signal.size, fs),
        }
        return features
    except Exception:
        features = _fallback_hrv_features(filtered, fs, prefix)
        features[f"{prefix}_peak_success_rate"] = 0.0
        return features


def _peak_success_rate(n_peaks: int, n_samples: int, fs: float) -> float:
    expected = (n_samples / fs) / 60.0 * 70.0
    if expected <= 0:
        return 0.0
    return float(min(n_peaks / expected, 1.0))
# Generated By AI End (Cursor)
