# Generated By AI Start (Cursor)
"""Accelerometry and motion features."""

from __future__ import annotations

import numpy as np

from wesad_arousal.preprocessing import safe_stat


def vector_magnitude(acc: np.ndarray) -> np.ndarray:
    arr = np.asarray(acc, dtype=float)
    if arr.ndim == 1:
        return np.abs(arr)
    if arr.ndim == 2 and arr.shape[1] >= 3:
        return np.sqrt(np.sum(arr[:, :3] ** 2, axis=1))
    return np.abs(arr.reshape(-1))


def extract_motion_features(acc: np.ndarray, fs: float, prefix: str = "motion") -> dict[str, float]:
    arr = np.asarray(acc, dtype=float)
    if arr.size == 0:
        return {
            f"{prefix}_vm_mean": 0.0,
            f"{prefix}_vm_std": 0.0,
            f"{prefix}_vm_energy": 0.0,
            f"{prefix}_vm_mad": 0.0,
        }

    vm = vector_magnitude(arr)
    return {
        f"{prefix}_vm_mean": safe_stat(vm, np.mean),
        f"{prefix}_vm_std": safe_stat(vm, np.std),
        f"{prefix}_vm_energy": safe_stat(vm, lambda x: np.mean(x ** 2)),
        f"{prefix}_vm_mad": safe_stat(vm, lambda x: np.median(np.abs(x - np.median(x)))),
    }


def extract_emg_features(emg: np.ndarray, fs: float, prefix: str = "emg") -> dict[str, float]:
    signal = np.asarray(emg, dtype=float).reshape(-1)
    if signal.size == 0:
        return {f"{prefix}_rms": 0.0, f"{prefix}_mad": 0.0, f"{prefix}_spectral_energy": 0.0}

    rms = safe_stat(signal, lambda x: np.sqrt(np.mean(x ** 2)))
    mad = safe_stat(signal, lambda x: np.median(np.abs(x - np.median(x))))
    try:
        from scipy import signal as scipy_signal

        freqs, power = scipy_signal.welch(signal, fs=fs, nperseg=min(len(signal), int(fs * 2)))
        spectral_energy = float(np.trapz(power, freqs))
    except Exception:
        spectral_energy = 0.0

    return {
        f"{prefix}_rms": rms,
        f"{prefix}_mad": mad,
        f"{prefix}_spectral_energy": spectral_energy,
    }
# Generated By AI End (Cursor)
