# Generated By AI Start (Cursor)
"""Body temperature features."""

from __future__ import annotations

import numpy as np

from wesad_arousal.preprocessing import safe_stat


def extract_temperature_features(temp: np.ndarray, fs: float, prefix: str = "temp") -> dict[str, float]:
    signal = np.asarray(temp, dtype=float).reshape(-1)
    if signal.size == 0:
        return {
            f"{prefix}_mean": 0.0,
            f"{prefix}_std": 0.0,
            f"{prefix}_slope": 0.0,
            f"{prefix}_range": 0.0,
        }

    x = np.arange(signal.size) / fs if fs > 0 else np.arange(signal.size)
    slope = 0.0
    if signal.size > 1:
        slope = float(np.polyfit(x, signal, 1)[0])

    return {
        f"{prefix}_mean": safe_stat(signal, np.mean),
        f"{prefix}_std": safe_stat(signal, np.std),
        f"{prefix}_slope": slope,
        f"{prefix}_range": float(np.max(signal) - np.min(signal)) if signal.size else 0.0,
    }
# Generated By AI End (Cursor)
