# Generated By AI Start (Cursor)
"""Sliding-window generation with label majority voting."""

from __future__ import annotations

from dataclasses import dataclass

import numpy as np
import pandas as pd

from wesad_arousal.labels import map_label_code, to_binary_label, valid_label_values


@dataclass
class WindowSpec:
    start_index: int
    end_index: int
    start_s: float
    end_s: float
    label_code: int
    label_name: str
    binary_label: int | None
    label_purity: float


def generate_windows(
    labels: np.ndarray,
    fs: float,
    window_seconds: float,
    step_seconds: float,
    cfg: dict,
    majority_threshold: float | None = None,
) -> list[WindowSpec]:
    threshold = majority_threshold
    if threshold is None:
        threshold = cfg["windowing"]["label_majority_threshold"]

    window_samples = int(window_seconds * fs)
    step_samples = int(step_seconds * fs)
    valid = valid_label_values(cfg)
    windows: list[WindowSpec] = []

    for start in range(0, len(labels) - window_samples + 1, step_samples):
        end = start + window_samples
        segment = labels[start:end]
        segment = segment[segment >= 0]
        if len(segment) == 0:
            continue

        counts = {code: int(np.sum(segment == code)) for code in valid}
        best_code = max(counts, key=counts.get)
        purity = counts[best_code] / len(segment)
        if purity < threshold:
            continue

        label_name = map_label_code(best_code, cfg)
        if label_name is None:
            continue

        windows.append(
            WindowSpec(
                start_index=start,
                end_index=end,
                start_s=start / fs,
                end_s=end / fs,
                label_code=best_code,
                label_name=label_name,
                binary_label=to_binary_label(label_name),
                label_purity=purity,
            )
        )
    return windows


def windows_to_dataframe(windows: list[WindowSpec], subject_id: str) -> pd.DataFrame:
    rows = []
    for idx, window in enumerate(windows):
        rows.append(
            {
                "subject_id": subject_id,
                "window_id": idx,
                "window_start_s": window.start_s,
                "window_end_s": window.end_s,
                "label_code": window.label_code,
                "label_name": window.label_name,
                "binary_label": window.binary_label,
                "label_purity": window.label_purity,
            }
        )
    return pd.DataFrame(rows)


def slice_signal_by_window(signal: np.ndarray, fs: float, window: WindowSpec) -> np.ndarray:
    start = int(window.start_s * fs)
    end = int(window.end_s * fs)
    end = min(end, len(signal))
    if start >= len(signal):
        return np.array([], dtype=float)
    return np.asarray(signal[start:end], dtype=float)
# Generated By AI End (Cursor)
